version: "3"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

  redshift:
    build: ./redshift
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5439:5432"

  redis:
    image: redis:3.2  # No higher than Elasticache latest
    ports:
      - "6379:6379"

  stripe:
    image: stripemock/stripe-mock:latest
    ports:
      - "12111:12111"

  localstack:
    image: localstack/localstack
    environment:
      SERVICES: "firehose,kinesis,lambda,s3,sqs,dynamodb"
    ports:
      - "4567-4583"

  frontend:
    image: node:12
    command: sh -c 'yarn && yarn dev'
    volumes:
      - "./HSReplay.net:/opt/hsreplay.net/source"
    working_dir: /opt/hsreplay.net/source
    environment:
      NODE_ENV: "development"
    ports:
      - "3000:3000"

  hsreplaynet-api-proxy:
    env_file: .env
    image: node:12
    command: sh -c "yarn && yarn run proxy ${HSREPLAYNET_SESSIONID} -p 8080"
    volumes:
      - "./hsreplaynet-dev-proxy:/opt/hsreplaynet-dev-proxy"
    working_dir: /opt/hsreplaynet-dev-proxy
    ports:
      - "8080:8080"

  django:
    build: .
    command: sh -c 'pipenv run ./manage.py runserver 0.0.0.0:8000'
    volumes:
      - "./HSReplay.net:/opt/hsreplay.net/source"
    working_dir: /opt/hsreplay.net/source
    ports:
      - "8000:8000"
    environment:
      PGHOST: "db"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIPENV_VENV_IN_PROJECT: "1"
      PYTHONUNBUFFERED: "1"
      SHELL: "/bin/bash"
      TESTS_REDIS_HOST: "redis"
      XDG_CACHE_HOME: "/opt/hsreplay.net/source/.venv/.cache"
    depends_on:
      - db
      - redshift
      - localstack
      - redis
      - stripe
      - hsreplaynet-api-proxy
